name: AI Assistant

on:
  issue_comment:
    types: [created]

# Prevent concurrent AI requests on the same issue
concurrency:
  group: ai-comment-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  run-ai-assistant:
    # Trigger on comments starting with '/ai ' from non-bot users.
    if: startsWith(github.event.comment.body, '/ai ') && github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout repository
      issues: write # Required to post comments
    steps:
      - name: Post processing notification
        id: processing_comment
        uses: actions/github-script@v7
        with:
          script: |
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: '🤖 Processing your AI request...'
            });
            core.setOutput('processing_comment_id', comment.data.id);

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @azure-rest/ai-inference@latest
          npm install @azure/core-auth@latest
          npm install @azure/core-sse@latest
          npm install @octokit/rest@^20.1.0
          npm install dotenv@^16.4.5

      - name: Run AI Commenter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          GH_AI_TOKEN: ${{ secrets.GH_AI_TOKEN }}
          PROCESSING_COMMENT_ID: ${{ steps.processing_comment.outputs.processing_comment_id }}
        run: node .github/scripts/aicomment.js